<?php

return [
    'categories' => [
        'fondations' => ['label' => 'Fondations', 'color' => '#1d4ed8'],
        'grand_livre' => ['label' => 'Grand livre', 'color' => '#7c3aed'],
        'tiers_ventes' => ['label' => 'Tiers & pièces', 'color' => '#c2410c'],
        'tresorerie' => ['label' => 'Trésorerie', 'color' => '#047857'],
        'pilotage' => ['label' => 'Pilotage', 'color' => '#b45309'],
        'fiscalite_actifs' => ['label' => 'Fiscalité & actifs', 'color' => '#be123c'],
        'gouvernance' => ['label' => 'Gouvernance', 'color' => '#475569'],
    ],

    'tables' => [
        'devises' => ['category' => 'fondations', 'label' => 'Devises', 'description' => 'Référentiel ISO des monnaies utilisées par les dossiers, pièces, paiements et écritures multidevises.'],
        'taux_changes' => ['category' => 'fondations', 'label' => 'Taux de change', 'description' => 'Historique daté des taux entre deux devises, avec la source ayant fourni chaque valeur.'],
        'referentiel_comptables' => ['category' => 'fondations', 'label' => 'Référentiels comptables', 'description' => 'Normes et plans réglementaires versionnés, par exemple SYSCOHADA ou IFRS.'],
        'dossiers_comptables' => ['category' => 'fondations', 'label' => 'Dossiers comptables', 'description' => 'Racine comptable du microservice. Chaque dossier correspond à une entreprise gérée par un service externe.'],
        'exercice_comptables' => ['category' => 'fondations', 'label' => 'Exercices comptables', 'description' => 'Cadres annuels de saisie, validation et clôture des opérations comptables.'],
        'periode_comptables' => ['category' => 'fondations', 'label' => 'Périodes comptables', 'description' => 'Découpage mensuel ou d’ajustement d’un exercice, avec état d’ouverture ou de verrouillage.'],

        'comptes' => ['category' => 'grand_livre', 'label' => 'Plan comptable', 'description' => 'Comptes généraux hiérarchiques qui portent toutes les imputations du grand livre.'],
        'journals' => ['category' => 'grand_livre', 'label' => 'Journaux', 'description' => 'Regroupent les écritures par nature et pilotent leurs séquences et comptes automatiques.'],
        'ecritures' => ['category' => 'grand_livre', 'label' => 'Écritures', 'description' => 'En-têtes des opérations en partie double, de leur brouillon jusqu’à la comptabilisation ou l’extourne.'],
        'ligne_ecritures' => ['category' => 'grand_livre', 'label' => 'Lignes d’écriture', 'description' => 'Mouvements débit ou crédit du grand livre, enrichis des tiers, taxes, devises et dimensions analytiques.'],
        'soldes_comptables' => ['category' => 'grand_livre', 'label' => 'Soldes comptables', 'description' => 'Projection périodique atomique des débits, crédits et soldes normaux ou anormaux par compte.'],
        'lettrages' => ['category' => 'grand_livre', 'label' => 'Lettrages', 'description' => 'Groupes d’apurement total ou partiel des mouvements d’un compte auxiliaire.'],
        'ligne_lettrages' => ['category' => 'grand_livre', 'label' => 'Lignes de lettrage', 'description' => 'Associent un montant précis de ligne d’écriture à un groupe de lettrage.'],

        'tiers' => ['category' => 'tiers_ventes', 'label' => 'Tiers', 'description' => 'Projection comptable minimale des clients, fournisseurs et autres contreparties externes.'],
        'coordonnees_bancaires_tiers' => ['category' => 'tiers_ventes', 'label' => 'Banques des tiers', 'description' => 'Coordonnées bancaires nécessaires au règlement des tiers sans dupliquer leur fiche métier.'],
        'pieces_comptables' => ['category' => 'tiers_ventes', 'label' => 'Pièces comptables', 'description' => 'Factures, avoirs, notes de débit et autres documents générateurs d’écritures.'],
        'ligne_pieces_comptables' => ['category' => 'tiers_ventes', 'label' => 'Lignes de pièce', 'description' => 'Détail quantitatif, fiscal, analytique et comptable de chaque pièce.'],
        'echeances' => ['category' => 'tiers_ventes', 'label' => 'Échéances', 'description' => 'Calendrier des montants dus permettant les règlements partiels et la balance âgée.'],

        'comptes_tresorerie' => ['category' => 'tresorerie', 'label' => 'Comptes de trésorerie', 'description' => 'Comptes bancaires et caisses reliés au plan comptable, à un journal et à une devise.'],
        'paiements' => ['category' => 'tresorerie', 'label' => 'Paiements', 'description' => 'Encaissements, décaissements, virements et remboursements comptabilisés.'],
        'affectations_paiements' => ['category' => 'tresorerie', 'label' => 'Affectations de paiement', 'description' => 'Ventilent un paiement sur une ou plusieurs pièces et échéances.'],
        'releves_bancaires' => ['category' => 'tresorerie', 'label' => 'Relevés bancaires', 'description' => 'Périmètres importés d’une banque avec soldes d’ouverture et de clôture.'],
        'operations_bancaires' => ['category' => 'tresorerie', 'label' => 'Opérations bancaires', 'description' => 'Lignes brutes issues des relevés avant leur rapprochement au grand livre.'],
        'rapprochements_bancaires' => ['category' => 'tresorerie', 'label' => 'Rapprochements', 'description' => 'Liens plusieurs-à-plusieurs entre opérations bancaires et mouvements comptables.'],

        'axes_analytiques' => ['category' => 'pilotage', 'label' => 'Axes analytiques', 'description' => 'Dimensions de pilotage telles que centre de coût, projet ou département.'],
        'comptes_analytiques' => ['category' => 'pilotage', 'label' => 'Valeurs analytiques', 'description' => 'Valeurs hiérarchiques utilisables dans chaque axe analytique.'],
        'budgets' => ['category' => 'pilotage', 'label' => 'Budgets', 'description' => 'Versions budgétaires d’un exercice servant à comparer prévisionnel et réalisé.'],
        'ligne_budgets' => ['category' => 'pilotage', 'label' => 'Lignes budgétaires', 'description' => 'Montants prévus par période, compte général et valeur analytique.'],

        'taxes' => ['category' => 'fiscalite_actifs', 'label' => 'Taxes', 'description' => 'Règles fiscales paramétrables, leurs taux, périodes de validité et comptes de liquidation.'],
        'declarations_fiscales' => ['category' => 'fiscalite_actifs', 'label' => 'Déclarations fiscales', 'description' => 'Synthèses périodiques de TVA, retenues et autres obligations déclaratives.'],
        'ligne_declarations_fiscales' => ['category' => 'fiscalite_actifs', 'label' => 'Lignes de déclaration', 'description' => 'Ventilation auditable d’une déclaration par taxe et case réglementaire.'],
        'categories_immobilisations' => ['category' => 'fiscalite_actifs', 'label' => 'Catégories d’actifs', 'description' => 'Règles, durées et comptes automatiques appliqués aux immobilisations.'],
        'immobilisations' => ['category' => 'fiscalite_actifs', 'label' => 'Immobilisations', 'description' => 'Registre patrimonial couvrant acquisition, mise en service, valeur nette et sortie.'],
        'amortissements' => ['category' => 'fiscalite_actifs', 'label' => 'Amortissements', 'description' => 'Échéances du plan d’amortissement et écritures de dotation correspondantes.'],
        'modeles_ecritures_recurrentes' => ['category' => 'fiscalite_actifs', 'label' => 'Écritures récurrentes', 'description' => 'Modèles planifiés pour loyers, abonnements, provisions et autres opérations périodiques.'],

        'verrouillages_comptables' => ['category' => 'gouvernance', 'label' => 'Verrouillages', 'description' => 'Interdictions de saisie par date et portée, indépendantes des clôtures de période.'],
        'documents_comptables' => ['category' => 'gouvernance', 'label' => 'Justificatifs', 'description' => 'Métadonnées et empreintes des pièces jointes probantes liées aux objets comptables.'],
        'journaux_audit' => ['category' => 'gouvernance', 'label' => 'Journal d’audit', 'description' => 'Trace append-only et chaînable des modifications comptables sensibles.'],
        'cles_idempotence' => ['category' => 'gouvernance', 'label' => 'Clés d’idempotence', 'description' => 'Dédupliquent les commandes API afin qu’une même demande ne soit traitée qu’une fois.'],
        'evenements_sortants' => ['category' => 'gouvernance', 'label' => 'Événements sortants', 'description' => 'Boîte de sortie transactionnelle pour publier les événements du microservice sans perte.'],
    ],

    // Ajout : phrases volontairement simples utilisées par le mode Découverte du visualiseur.
    'simple_descriptions' => [
        'devises' => 'La liste des monnaies, comme le franc CFA, l’euro ou le dollar.',
        'taux_changes' => 'Dit combien vaut une monnaie quand on la transforme en une autre.',
        'referentiel_comptables' => 'Le livre de règles que la comptabilité doit suivre.',
        'dossiers_comptables' => 'La grande boîte qui rassemble toute la comptabilité d’une entreprise.',
        'exercice_comptables' => 'Une année de comptabilité, avec une date de début et de fin.',
        'periode_comptables' => 'Un petit morceau de l’année, souvent un mois.',
        'comptes' => 'Des tiroirs qui rangent l’argent par sujet : banque, ventes, achats, taxes…',
        'journals' => 'Des cahiers qui regroupent les opérations du même genre.',
        'ecritures' => 'Une opération comptable complète, comme une vente ou un achat.',
        'ligne_ecritures' => 'Un côté débit ou crédit d’une opération. Les deux côtés doivent avoir le même total.',
        'soldes_comptables' => 'Le compteur qui montre combien est entré et sorti de chaque compte.',
        'lettrages' => 'Une agrafe virtuelle qui relie une facture à ce qui la paie.',
        'ligne_lettrages' => 'La petite partie d’une écriture utilisée par une agrafe de lettrage.',
        'tiers' => 'Les personnes ou organisations avec lesquelles on achète ou vend.',
        'coordonnees_bancaires_tiers' => 'Les informations bancaires utilisées pour payer un client ou un fournisseur.',
        'pieces_comptables' => 'Les factures, avoirs et autres documents qui expliquent une opération.',
        'ligne_pieces_comptables' => 'Les articles ou services écrits un par un sur une facture.',
        'echeances' => 'Les dates auxquelles une somme doit être payée.',
        'comptes_tresorerie' => 'Les banques et caisses dans lesquelles l’argent est gardé.',
        'paiements' => 'L’argent reçu ou envoyé.',
        'affectations_paiements' => 'Dit quelle partie d’un paiement règle quelle facture.',
        'releves_bancaires' => 'Une page envoyée par la banque qui raconte les mouvements du compte.',
        'operations_bancaires' => 'Une entrée ou une sortie d’argent vue sur le relevé bancaire.',
        'rapprochements_bancaires' => 'Relie une ligne de banque à la même opération dans la comptabilité.',
        'axes_analytiques' => 'Des façons de classer les dépenses, par exemple par projet ou équipe.',
        'comptes_analytiques' => 'Les choix disponibles dans un classement, comme “Projet école”.',
        'budgets' => 'Le plan de l’argent que l’on pense recevoir ou dépenser.',
        'ligne_budgets' => 'Une petite partie du budget pour un mois et un sujet précis.',
        'taxes' => 'Les règles qui calculent les impôts et taxes.',
        'declarations_fiscales' => 'Le résumé des taxes à déclarer à l’administration.',
        'ligne_declarations_fiscales' => 'Le détail qui explique chaque nombre d’une déclaration de taxes.',
        'categories_immobilisations' => 'Les familles de biens qui durent longtemps, comme les voitures ou ordinateurs.',
        'immobilisations' => 'Les biens chers utilisés pendant plusieurs années.',
        'amortissements' => 'La petite part de valeur qu’un bien perd au fil du temps.',
        'modeles_ecritures_recurrentes' => 'Des opérations qui se répètent automatiquement, comme un loyer mensuel.',
        'verrouillages_comptables' => 'Des cadenas qui empêchent de changer une période terminée.',
        'documents_comptables' => 'Les fichiers qui servent de preuve, comme une photo de facture.',
        'journaux_audit' => 'Le carnet de bord qui garde la trace de chaque changement important.',
        'cles_idempotence' => 'Des tickets uniques qui empêchent de faire deux fois la même demande.',
        'evenements_sortants' => 'Les messages prêts à prévenir les autres services qu’une chose est arrivée.',
    ],

    // Ajout : documentation métier des déclencheurs affichée dans les modes Découverte et Expert.
    'triggers' => [
        ['name' => 'ligne_ecritures_actualiser_parent', 'source' => 'ligne_ecritures', 'target' => 'ecritures', 'event' => 'Ajout, modification ou suppression', 'title' => 'Additionner l’écriture', 'simple' => 'Quand une ligne change, le total débit et le total crédit de l’écriture sont recomptés.', 'why' => 'Ainsi, le nombre affiché sur l’enveloppe est toujours la somme de ce qu’elle contient.'],
        ['name' => 'ligne_ecritures_valider_coherence', 'source' => 'ligne_ecritures', 'target' => 'comptes', 'event' => 'Avant ajout ou déplacement', 'title' => 'Vérifier le bon compte', 'simple' => 'La ligne doit utiliser un compte du même dossier et ce compte doit accepter des opérations.', 'why' => 'Cela évite de ranger de l’argent dans le mauvais tiroir.'],
        ['name' => 'ecritures_valider_avant_comptabilisation', 'source' => 'ecritures', 'target' => 'periode_comptables', 'event' => 'Avant comptabilisation', 'title' => 'Contrôler l’équilibre', 'simple' => 'Le débit et le crédit doivent être égaux, avec au moins deux lignes et un mois encore ouvert.', 'why' => 'Une opération incomplète ne peut pas devenir officielle.'],
        ['name' => 'ecritures_projeter_soldes', 'source' => 'ecritures', 'target' => 'soldes_comptables', 'event' => 'Après comptabilisation', 'title' => 'Mettre les compteurs à jour', 'simple' => 'Une écriture officielle ajoute ses débits et crédits aux compteurs des comptes.', 'why' => 'Les soldes restent à jour sans demander à l’application de refaire le calcul.'],
        ['name' => 'ligne_pieces_actualiser_parent', 'source' => 'ligne_pieces_comptables', 'target' => 'pieces_comptables', 'event' => 'Ajout, modification ou suppression', 'title' => 'Recalculer la facture', 'simple' => 'Quand un article change, les sous-totaux, taxes et total de la facture sont recomptés.', 'why' => 'Le total de la facture correspond toujours à ses lignes.'],
        ['name' => 'paiements_initialiser_solde', 'source' => 'paiements', 'target' => 'paiements', 'event' => 'Avant ajout ou changement du montant', 'title' => 'Préparer le paiement', 'simple' => 'Un nouveau paiement commence entièrement disponible.', 'why' => 'On sait exactement quelle somme peut encore servir à payer une facture.'],
        ['name' => 'affectations_paiements_valider', 'source' => 'affectations_paiements', 'target' => 'paiements', 'event' => 'Avant ajout ou modification', 'title' => 'Bloquer le trop-payé', 'simple' => 'On ne peut pas utiliser plus d’argent que le paiement, la facture ou l’échéance ne le permet.', 'why' => 'Aucun reste ne peut passer sous zéro.'],
        ['name' => 'affectations_paiements_actualiser_parents', 'source' => 'affectations_paiements', 'target' => 'pieces_comptables', 'event' => 'Après ajout, modification ou suppression', 'title' => 'Mettre tous les restes à jour', 'simple' => 'La somme disponible, la facture restant à payer et l’échéance sont recalculées ensemble.', 'why' => 'Tous les écrans racontent la même histoire.'],
        ['name' => 'lettrages_initialiser_totaux', 'source' => 'lettrages', 'target' => 'lettrages', 'event' => 'Avant ajout', 'title' => 'Créer une agrafe vide', 'simple' => 'Un nouveau lettrage commence avec zéro au débit et zéro au crédit.', 'why' => 'Les totaux viennent seulement des lignes réellement reliées.'],
        ['name' => 'ligne_lettrages_valider', 'source' => 'ligne_lettrages', 'target' => 'ligne_ecritures', 'event' => 'Avant ajout ou modification', 'title' => 'Limiter le lettrage', 'simple' => 'Une ligne ne peut pas être utilisée pour plus que son montant.', 'why' => 'La même somme ne peut pas payer deux choses.'],
        ['name' => 'ligne_lettrages_actualiser_parent', 'source' => 'ligne_lettrages', 'target' => 'lettrages', 'event' => 'Après ajout, modification ou suppression', 'title' => 'Recalculer l’agrafe', 'simple' => 'Les totaux débit, crédit et le reste du lettrage sont recomptés.', 'why' => 'Le lettrage indique tout de suite s’il est complet.'],
        ['name' => 'operations_bancaires_initialiser_solde', 'source' => 'operations_bancaires', 'target' => 'operations_bancaires', 'event' => 'Avant ajout ou changement du montant', 'title' => 'Préparer la ligne bancaire', 'simple' => 'Une nouvelle ligne de banque commence entièrement à rapprocher.', 'why' => 'On voit ce qu’il reste à retrouver dans la comptabilité.'],
        ['name' => 'rapprochements_bancaires_valider', 'source' => 'rapprochements_bancaires', 'target' => 'ligne_ecritures', 'event' => 'Avant ajout ou modification', 'title' => 'Bloquer le double rapprochement', 'simple' => 'On ne peut pas rapprocher plus que la banque ou la ligne comptable ne contient.', 'why' => 'Un même euro ou franc CFA ne peut pas être coché deux fois.'],
        ['name' => 'rapprochements_bancaires_actualiser_parents', 'source' => 'rapprochements_bancaires', 'target' => 'operations_bancaires', 'event' => 'Après ajout, modification ou suppression', 'title' => 'Recalculer le rapprochement', 'simple' => 'Les restes de la banque et de la ligne comptable sont mis à jour ensemble.', 'why' => 'Le statut devient automatiquement non, partiellement ou totalement rapproché.'],
        ['name' => 'immobilisations_initialiser_valeur', 'source' => 'immobilisations', 'target' => 'immobilisations', 'event' => 'Avant ajout ou changement du coût', 'title' => 'Donner sa valeur au bien', 'simple' => 'Un nouveau bien vaut son prix d’achat, puis garde une valeur qui ne descend jamais sous sa valeur finale prévue.', 'why' => 'Un bien ne peut pas perdre plus de valeur qu’il n’en possède.'],
        ['name' => 'amortissements_actualiser_immobilisation', 'source' => 'amortissements', 'target' => 'immobilisations', 'event' => 'Après ajout, modification ou suppression', 'title' => 'Faire vieillir le bien', 'simple' => 'Chaque amortissement officiel réduit la valeur restante du bien.', 'why' => 'La valeur actuelle est toujours calculée depuis les amortissements réels.'],
        ['name' => 'ligne_declarations_actualiser_parent', 'source' => 'ligne_declarations_fiscales', 'target' => 'declarations_fiscales', 'event' => 'Après ajout, modification ou suppression', 'title' => 'Recalculer les taxes', 'simple' => 'Les taxes collectées, déductibles, dues ou à reporter sont recomptées.', 'why' => 'Une taxe à récupérer devient un crédit positif, jamais une dette négative.'],
        ['name' => 'ligne_budgets_actualiser_parent', 'source' => 'ligne_budgets', 'target' => 'budgets', 'event' => 'Après ajout, modification ou suppression', 'title' => 'Additionner le budget', 'simple' => 'Quand une prévision change, les totaux débit et crédit du budget sont recomptés.', 'why' => 'Le grand total est toujours la somme des petites prévisions.'],
    ],

    // Ajout : exemples guidés et petit dictionnaire pour expliquer les mots comptables sans prérequis.
    'stories' => [
        ['icon' => '🧾', 'title' => 'Une facture de 125', 'steps' => ['Les lignes indiquent 100 de service et 25 de taxe.', 'Le déclencheur calcule automatiquement un total de 125.', 'Un paiement de 80 laisse 45 à payer, jamais −45.']],
        ['icon' => '⚖️', 'title' => 'Une vente équilibrée', 'steps' => ['125 est ajouté au débit de la banque.', '125 est ajouté au crédit des ventes.', 'Comme les deux côtés valent 125, l’écriture peut devenir officielle.']],
        ['icon' => '🏦', 'title' => 'Retrouver un paiement', 'steps' => ['La banque montre un mouvement de 80.', 'Le rapprochement le relie à la ligne comptable de 80.', 'Le reste à rapprocher devient zéro, sans pouvoir descendre plus bas.']],
    ],
    'glossary' => [
        ['term' => 'Débit', 'simple' => 'Le côté gauche d’une opération comptable. Pour une banque, il représente souvent de l’argent qui entre.'],
        ['term' => 'Crédit', 'simple' => 'Le côté droit d’une opération comptable. Pour une vente, il représente souvent ce qui a été gagné.'],
        ['term' => 'Solde', 'simple' => 'Ce qu’il reste après avoir comparé les entrées et les sorties.'],
        ['term' => 'Déclencheur', 'simple' => 'Un petit robot dans la base de données qui agit automatiquement quand une ligne change.'],
        ['term' => 'Lettrage', 'simple' => 'Une agrafe virtuelle entre une somme due et la somme qui la règle.'],
        ['term' => 'Rapprochement', 'simple' => 'La vérification qu’un mouvement de banque existe aussi dans la comptabilité.'],
    ],
];
